version: '3'

services:  
  meencuentrobien:
    image: germanramos/meencuentrobien:latest
    restart: unless-stopped
    env_file:
      - ../meencuentrobien.sh
    volumes:
      - meencuentrobien:/data

volumes:
  meencuentrobien:
